### ISSUE TITLE
How to establish wordnet(hierarchical) embedding matrix?

### ISSUE THREAD

**Issue by hooraid** [AnjanDutta/sem-pcyc#1]
in paper, 
"For a set S of
nodes in a dictionary D, similarities between every class c and all the other nodes in S determine the entries of the class embedding vector. S considers all the nodes on the path from each node in D to its highest level ancestor."

But, one word can contain lots of homonyms in wordnet. 
(for example, tank.n.01: an enclosed armored military vehicle; has a cannon and moves on caterpillar treads, tank.n.05: a cell for violent prisoners, tank.v.01: store in a tank by causing to flow into it)

So, I wonder how to calculate a path(similarity score) between two nodes in wordnet more specifically. (how to address the problem about homonyms)

thank you :)

**Comment by AnjanDutta** [comment]
Hi there,
Thanks for your message, have a look at the bottom of this page: http://www.nltk.org/howto/wordnet.html. You can find the definition of various similarity measures.
I hope this helps.
