### ISSUE TITLE
model not found during training

### ISSUE THREAD

**Issue by Anurag14** [AnjanDutta/sem-pcyc#13]
Hi!
Thanks for helping out on previous issue. I am trying to train the model from scratch. The code is giving me error on word 2 vec model being missing. I would really appreciate if you could provide the links to semantic models you used. Can I use sketchy pre-trained model and put it in this folder and run the code? 
```
python3 src/train.py --dataset Sketchy_extended --gzs-sbir --dim-out 64 --semantic-models word2vec-google-news --epochs 1000 --early-stop 200 --lr 0.0001
Parameters:	Namespace(batch_size=128, dataset='Sketchy_extended', dim_out=64, early_stop=200, epoch_size=100, epochs=1000, filter_sketch=False, gamma=0.1, gzs_sbir=True, im_sz=224, lambda_disc_im=0.5, lambda_disc_se=0.25, lambda_disc_sk=0.5, lambda_gen_adv=1.0, lambda_gen_cls=1.0, lambda_gen_cyc=1.0, lambda_gen_reg=0.1, lambda_im=10.0, lambda_regular=0.001, lambda_se=10.0, lambda_sk=10.0, log_interval=1, lr=0.0001, milestones=[], momentum=0.9, ngpu=1, num_workers=4, number_qualit_results=200, save_best_results=False, save_image_results=False, semantic_models=['word2vec-google-news'], sk_sz=224, split_eccv_2018=False, test=False)
Checkpoint path: /home/iacvlab/anurag/novelty/sem-pcyc/CheckPoints/Sketchy/generalized/word2vec-google-news/64
Logger path: /home/iacvlab/anurag/novelty/sem-pcyc/LogFiles/Sketchy/generalized/word2vec-google-news/64
Result path: /home/iacvlab/anurag/novelty/sem-pcyc/Results/Sketchy/generalized/word2vec-google-news/64
Loading data...Done
Initializing model variables...Done
Initializing trainable models...Done
Defining optimizers...Done
Defining losses...Done
Initializing variables...Done
Setting logger...Done
Checking cuda...*Cuda exists*...Done
No best model found at '/home/iacvlab/anurag/novelty/sem-pcyc/CheckPoints/Sketchy/generalized/word2vec-google-news/64/model_best.pth'. Exiting...
```

**Comment by AnjanDutta** [comment]
`--gzs-sbir` activates testing mode. So remove it and then train it. I haven't provided the model only for word2vec, you have to train it.

**Comment by Anurag14** [comment]
Firstly, Thank you. I realised this later on. Are the semantic models used for generalized zero shot during testing same as that for normal zero shot setting on respective datasets? I am unable to replicate results for generalised setting. The results that we are getting are very different from the ones reported. We would really appreciate your help !

**Comment by AnjanDutta** [comment]
set `perc = 1.0`, I kept it `perc=0.2` because many others complain about memory overflow. I should have done it in a different way. Anyways, I shall modify but ideally `perc` should be equal to `1.0`.
