### ISSUE TITLE
Details of training base feature extractor

### ISSUE THREAD

**Issue by haowang1992** [AnjanDutta/sem-pcyc#14]
Could you provide the details to train the vgg feature extractor? It is key of retrieval pefromance but I can not reproduce the model totally! I think it will help anybody who will use this code to train their own dataset.

**Comment by Anurag14** [comment]
The paper doesn't mention anything about the training of vgg.  However if you want to train from scratch you can keep ```pretrained=True``` and experiment with ```fine_tune=True/False```. Hopefully finetuning vgg should replicate the numbers.

**Comment by haowang1992** [comment]
Hi, I think the pre-trained vgg model was separately trained on sketch classification task, as illustrated in the paper. Will the pretraining just on Sketchy,TUBerlin dataset, their combination or extra sketch-image dataset? Hope the authors provide more details for the community!

**Comment by AnjanDutta** [comment]
Hello @haowang1992 , I already provided scripts for training image and sketch model some weeks back, they are in the src/utils folder. Please have a look on them.

**Comment by Chandan-IITI** [comment]
Hello @AnjanDutta, I have tried those scripts. However, I am unable to find VGGNetFeats or ResNet50Feats or SEResNet50Feats, which is mentioned in src/utils/train_image.py as

`from models import VGGNetFeats, ResNet50Feats, SEResNet50Feats`

Although, the VGGNetFeats is available in  src/models.py but with different arguments:

Required in src/utils/train_image.py: 
` model = VGGNetFeats(num_classes=len(dict_clss), pretrained=True, finetune_feats=False, finetune_class=True)`

Available in src/models.py:
`class VGGNetFeats(nn.Module):
    def __init__(self, pretrained=True, finetune=True):`
    
I might have misunderstood. Please let me know how to run the scripts available in src/utils/train_image.py.
