### ISSUE TITLE
Has the data been normalized?

### ISSUE THREAD

**Issue by silvia1993** [AnjanDutta/sem-pcyc#2]
I notice that the only transformations made on the data are:

transform_image = transforms.Compose([transforms.Resize((args.im_sz, args.im_sz)), transforms.ToTensor()])

Why do you not perform a normalization using the standard deviation and the mean of ImageNet?
transforms.Normalize([0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

Thank you! :)

**Comment by AnjanDutta** [comment]
No, we didn't add any other data normalisation.
