### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by jiangyanjavawin** [AnjanDutta/sem-pcyc#21]
Hello sir,Thans for your code,when I am trying to train the model,I find the Gan loss is bigger than 200,I want to know is that true?or something is wrong?If you have any ieda about it,please let me konw.Thank you very much. 
And I am also want to know what' s the meaning of the function of get_coarse_grained_samples()?

**Comment by zxh19976666** [comment]
hello  your code is successful to run？ If you did it  .could you help me?
thank you
