### ISSUE TITLE
about data split

### ISSUE THREAD

**Issue by bebory** [AnjanDutta/sem-pcyc#22]
Could you tell me how you split Sketchy and Tu-Berline dataset? Which categories do you pick out as the test set?

**Comment by neouyghur** [comment]
@AnjanDutta @bebory I created these based on their code:
**Sketchy test:**

1. bear
2. bell
3. cannon
4. door
5. eyeglasses
6. geyser
7. guitar
8. hamburger
9. jack_o_lantern
10. lobster
11. motorcycle
12. mushroom
13. pear
14. racket
15. rhinoceros
16. saw
17. saxophone
18. spoon
19. squirrel
20. tank
21. teapot
22. tiger
23. trumpet
24. violin
25. wheelchair

**TU-Berlin test:**

1. backpack
2. bicycle
3. bookshelf
4. cabinet
5. calculator
6. castle
7. couch
8. dolphin
9. door_handle
10. duck
11. eyeglasses
12. fire_hydrant
13. flying_saucer
14. foot
15. hedgehog
16. knife
17. octopus
18. pear
19. purse
20. rollerblades
21. sailboat
22. snail
23. snake
24. snowman
25. swan
26. tablelamp
27. traffic_light
28. truck
29. umbrella
30. walkie_talkie

**Comment by bebory** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Osman Tursun"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 上午9:02
收件人: "AnjanDutta/sem-pcyc"<sem-pcyc@noreply.github.com&gt;; 
抄送: "周健"<2239131181@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [AnjanDutta/sem-pcyc] about data split (#22)





 
@AnjanDutta @bebory I created these based on their code:
 Sketchy test:
  
bear
 
bell
 
cannon
 
door
 
eyeglasses
 
geyser
 
guitar
 
hamburger
 
jack_o_lantern
 
lobster
 
motorcycle
 
mushroom
 
pear
 
racket
 
rhinoceros
 
saw
 
saxophone
 
spoon
 
squirrel
 
tank
 
teapot
 
tiger
 
trumpet
 
violin
 
wheelchair
  
TU-Berlin test:
  
backpack
 
bicycle
 
bookshelf
 
cabinet
 
calculator
 
castle
 
couch
 
dolphin
 
door_handle
 
duck
 
eyeglasses
 
fire_hydrant
 
flying_saucer
 
foot
 
hedgehog
 
knife
 
octopus
 
pear
 
purse
 
rollerblades
 
sailboat
 
snail
 
snake
 
snowman
 
swan
 
tablelamp
 
traffic_light
 
truck
 
umbrella
 
walkie_talkie

**Comment by neouyghur** [comment]
@bebory My pleasure, but It would be better if the author can confirm its correctness.
