### ISSUE TITLE
About downloading datasets

### ISSUE THREAD

**Issue by rajangyawali** [AnjanDutta/sem-pcyc#23]
I could not download the datasets in google colab as mentioned in download_datasets.sh and config.ini . Is there any requirement to change in sh file ?

**Comment by minhkhoi1026** [comment]
Yeah, in config.ini file you need to specified the path for dataset download and model download, and the most important info **host name**.
In your case to work with Colab, simply run this Python code to get <hostname\> of the current machine:
```
import os
myhost = os.uname()[1]
print(myhost)
```
Assume I get the hostname = 9ab8bcf, and my directory structure in Colab look like below:
```
content
├── sem-pcyc
│   ├── data
│   ├── aux
│   ├── download_dataset.sh
│   ├── download_model.sh
│   └──  config.ini
```
then my config.ini will look like below:
```
[9ab8bcf]
path_dataset = /content/sem-pcyc/data
path_aux = /content/sem-pcyc/aux
```
Hope it useful for you.

**Comment by pSGAme** [comment]
Hi, sir. Could you please share the link to download the Sketchy Extended dataset and TU-Berlin Image dataset?
