### ISSUE TITLE
About the number of images and sketches

### ISSUE THREAD

**Issue by tiangarin** [AnjanDutta/sem-pcyc#25]
First of all, thank you for your excellent work. 
I checked the sample number for both datasets with the following command:
`print(len(glob.glob(r'/***/ZS_SBIR/sem-pcyc/Datasets/Data/Sketchy/sketch/tx_000000000000/*/*.png')), '\n')`
`print(len(glob.glob(r'/***/ZS_SBIR/sem-pcyc/Datasets/Data/Sketchy/extended_photo/*/*.jpg')), '\n')`
`print(len(glob.glob(r'/***/ZS_SBIR/sem-pcyc/Datasets/Data/TU-Berlin/sketches/*/*.png')), '\n')`
`print(len(glob.glob(r'/***/ZS_SBIR/sem-pcyc/Datasets/Data/TU-Berlin/images/*/*.jpg')), '\n')`
And I got 75481,73002,20000,204070. 
So, I want to know why the number of sketches of Sketchy and the number of images of TU-Berlin is not exactly the same as the paper say.
Thank you in advance for your answers.

**Comment by sahilkhose** [comment]
Running it now got me the following numbers:
75481, 73002, 20000, 6115

**Comment by sahilkhose** [comment]
75481, 73002, 20000, 204070
after removing the png/jpg extensions
