### ISSUE TITLE
sem_dim issue

### ISSUE THREAD

**Issue by mwmw7** [AnjanDutta/sem-pcyc#28]
hello I am Branden 
your paper and code  were perfect but
 
The below part is not clear I think 

why do you use += for this?

train.py line 80  

**sem_dim += list(np.load(fi, allow_pickle=True).item().values())[0].shape[0]**

```
    for f in args.semantic_models:
        fi = os.path.join(path_aux, 'Semantic', args.dataset, f + '.npy')
        files_semantic_labels.append(fi)
        sem_dim += list(np.load(fi, allow_pickle=True).item().values())[0].shape[0]
```

**Comment by AnjanDutta** [comment]
This is because we are combining semantic embeddings. Therefore, the dimension of semantic embeddings should be added.

**Comment by mwmw7** [comment]
But I use two  .npy files  like below
```
--semantic-models word2vec-google-news plus_words
```

and  each embedding dimension is 300

but "+=" this operation make sem_dim 600 so 

below two-part get an error

1. model.py line 394
```
   se = np.zeros((len(cl), self.sem_dim), dtype=np.float32)
            for i, c in enumerate(cl):
                se_c = np.array([], dtype=np.float32)
                for s in self.sem:
                    se_c = np.concatenate((se_c, s.get(c).astype(np.float32)), axis=0)
                se[i] = se_c
            se = torch.from_numpy(se)
```
**se[i] = se_c**

---------------------------------------------------------------------------------------------------------------------

2. model.py line 211
```
        self.aut_enc = AutoEncoder(dim=self.sem_dim, hid_dim=self.dim_out, nlayer=1)

```

So I think this "+=" should be changed to "=" 

Can I get your opinion?
