### ISSUE TITLE
Test with my data set.

### ISSUE THREAD

**Issue by 97-tianyan** [AnjanDutta/sem-pcyc#3]
1.Can I test with my own data set?There are no restrictions on the form of my data set.
2.I'm not sure what's the difference between your training and your tests.The model was given during the training.    Normally, training should be model-free，The test was done using a training model.

**Comment by AnjanDutta** [comment]
Yes, you should able to test on your own dataset as well. The train script also allows to test the model. I agree they are redundant.

**Comment by 97-tianyan** [comment]
Thank you very much for your reply, and use email.

First,I only put three categories on my own data set,And then I get this error.I don't know why.

Second,My ultimate goal is to test only one category, and I don't know if I need to retrain the model.

Can you tell me what to do if I need to change the code?





At 2019-09-04 17:28:13, "Anjan Dutta" <notifications@github.com> wrote:


Yes, you should able to test on your own dataset as well. The train script also allows to test the model. I agree they are redundant.

**Comment by AnjanDutta** [comment]
For all the sketches and images, first you have to get the embeddings and then compute the metric. Kindly have a look on the test code.

**Comment by 97-tianyan** [comment]
Hello! After a holiday thinking, I still can't solve this problem.The error code is as follows.I don't know why there are 100 categories in the test.

`RuntimeError: Error(s) in loading state_dict for SEM_PCYC:
        size mismatch for classifier_sk.weight: copying a param with shape t00, 512]) from checkpoint, the shape in current model is torch.Size([62, 512
        size mismatch for classifier_im.weight: copying a param with shape t00, 512]) from checkpoint, the shape in current model is torch.Size([62, 512
        size mismatch for classifier_se.weight: copying a param with shape t00, 64]) from checkpoint, the shape in current model is torch.Size([62, 64])`

**Comment by AnjanDutta** [comment]
You have used 62 as a size, so for that you have to retrain a model. You cannot use the pretrained model in this case.
