### ISSUE TITLE
Use your own data set for training

### ISSUE THREAD

**Issue by 97-tianyan** [AnjanDutta/sem-pcyc#5]
Hello, why did I make this mistake by training with my own data set？   I've only added two additional categories out of 125.
`Traceback (most recent call last):
  File "src/train.py", line 358, in <module>
    main()
  File "src/train.py", line 230, in main
    losses = train(train_loader, sem_pcyc_model, epoch, args)
  File "src/train.py", line 323, in train
    loss = sem_pcyc_model.optimize_params(sk, im, cl)
  File "/home/zhuyabin/sem-pcyc/src/models.py", line 367, in optimize_params
    se_c = np.concatenate((se_c, s.get(c).astype(np.float32)), axis=0)
AttributeError: 'NoneType' object has no attribute 'astype'
`

**Comment by AnjanDutta** [comment]
Which new classes are you using? If you are using those new classes whose semantic embeddings are not available, you can get this type of errors Let me know which classes are you using.

**Comment by 97-tianyan** [comment]
for example!  Such as bird,car,boy,people,human,soccer,tiger and so on .If these cannot be embedded, how can I train my dataset?

**Comment by AnjanDutta** [comment]
These categories are in TU-Berlin or Sketchy, so I haven't provided the word embeddings of these categories. If you want to train on new classes, you have to gather their sketch, image and word embeddings, and organize them as I did in the case of Sketchy or TU-Berlin
