### ISSUE TITLE
How to do semantic embedding

### ISSUE THREAD

**Issue by 97-tianyan** [AnjanDutta/sem-pcyc#6]
Hello, can I know how to do semantic embedding? Because I want to train my data set.Then test .

I have collected sketches, pictures and semantic information.

**Comment by AnjanDutta** [comment]
One way of doing so is to extract the label embedding using word2vec (with google news, glove etc.) See the attached code for doing that. 

`#!/usr/bin/python3
# -*- coding: utf-8 -*-

import argparse
import numpy as np
import re
import os
import glob
import gensim.downloader as api
import utils


def create_wordemb(root_path, type='word2vec-google-news-300'):

    clss = glob.glob(os.path.join(root_path, '*'))
    clss = [c.split('/')[-1] for c in clss if os.path.isdir(c)]
    available_type = ['word2vec-google-news-300', 'fasttext-wiki-news-subwords-300', 'glove-wiki-gigaword-300']
    if type not in available_type:
        print("Type specified does not exist.")
        exit()
    model = api.load(type).wv

    lv = len(model['airplane'])  # for knowing the length of vector

    wordemb = dict()
    # synonym dictionary
    syn_dict = utils.get_synonym()
    for cls in clss:
        cls_tmp = re.sub('[)(]', '', cls)
        if cls_tmp in model.vocab:
            ws = [cls_tmp]
        elif cls_tmp in syn_dict.keys():
            ws = syn_dict[cls_tmp].split('_')
        else:
            ws = cls_tmp.split('_')
        v = np.zeros((len(ws), lv))
        for i, w in enumerate(ws):
            if w in model.vocab:
                v[i, :] = model[w]
            else:
                print(w)
        wordemb.update({cls: np.mean(v, axis=0)})
    return wordemb


def main():

    # Parse options for processing
    parser = argparse.ArgumentParser(description='Generate word2vec representation.')

    parser.add_argument('--dataset', default='Sketchy', help='Name of the dataset')
    parser.add_argument('--type', default='word2vec-google-news-300', help='Type of word2vec model')
    parser.add_argument('--save-dir', default='/home/adutta/Workspace/SemCycGenZ2SIR/Semantic', help='')

    # Parse the arguments
    args = parser.parse_args()

    # Read the config file and
    config = utils.read_config()
    path_dataset = config['path_dataset']

    if args.dataset == 'Sketchy':
        sketch_dir = 'sketch'
        sketch_sd = 'tx_000000000000'
    elif args.dataset == 'TU-Berlin':
        sketch_dir = 'sketches'
        sketch_sd = ''
    elif args.dataset == 'QuickDraw':
        sketch_dir = 'sketches'
        sketch_sd = ''
    else:
        sketch_dir = ''
        sketch_sd = ''
    root_path = os.path.join(path_dataset, args.dataset, sketch_dir, sketch_sd)
    save_path = os.path.join(args.save_dir, args.dataset)

    wordemb = create_wordemb(root_path, args.type)
    if not os.path.isdir(save_path):
        os.makedirs(save_path)
    np.save(os.path.join(save_path, args.type + '.npy'), wordemb)


if __name__ == '__main__':

    main()`

**Comment by AnjanDutta** [comment]
One way of doing so is to extract the label embedding using word2vec (with google news, glove etc.) See the attached code for doing that. I hope this helps :)

`def create_wordemb(root_path, type='word2vec-google-news-300'):

    clss = glob.glob(os.path.join(root_path, '*'))
    clss = [c.split('/')[-1] for c in clss if os.path.isdir(c)]
    available_type = ['word2vec-google-news-300', 'fasttext-wiki-news-subwords-300', 'glove-wiki-gigaword-300']
    if type not in available_type:
        print("Type specified does not exist.")
        exit()
    model = api.load(type).wv

    lv = len(model['airplane'])  # for knowing the length of vector

    wordemb = dict()
    # synonym dictionary
    syn_dict = utils.get_synonym()
    for cls in clss:
        cls_tmp = re.sub('[)(]', '', cls)
        if cls_tmp in model.vocab:
            ws = [cls_tmp]
        elif cls_tmp in syn_dict.keys():
            ws = syn_dict[cls_tmp].split('_')
        else:
            ws = cls_tmp.split('_')
        v = np.zeros((len(ws), lv))
        for i, w in enumerate(ws):
            if w in model.vocab:
                v[i, :] = model[w]
            else:
                print(w)
        wordemb.update({cls: np.mean(v, axis=0)})
    return wordemb`

**Comment by 97-tianyan** [comment]
Can you tell me how to use this code?
I found the following line in the code
`# synonym dictionary
syn_dict = utils.get_synonym()`
But there is no get_synonym in your utils.py

**Comment by 97-tianyan** [comment]
sorry ! code as follow!
`syn_dict = utils.get_synonym()`

**Comment by AnjanDutta** [comment]
Here is the get_synonym code, but it will be different if you have different dataset:

`
def get_synonym():

    syn = dict()
    syn['axe'] = 'hatchet'
    syn['bear_animal'] = 'bear'
    syn['beer_mug'] = 'stein'
    syn['bottle_opener'] = 'opener'
    syn['computer_monitor'] = 'monitor'
    syn['crane_machine'] = 'crane'
    syn['head_phones'] = 'headphones'
    syn['hot_dog'] = 'hotdog'
    syn['mouse_animal'] = 'rat'
    syn['paper_clip'] = 'paperclip'
    syn['power_outlet'] = 'socket'
    syn['race_car'] = 'racecar'
    syn['sponge_bob'] = 'spongebob'
    syn['wrist_watch'] = 'watch'

    return syn
`

**Comment by 97-tianyan** [comment]
Thanks!  
Should the code you sent before be a separate python file?     Or should it be in the train.py file?

**Comment by jiangyanjavawin** [comment]
> 
> 
> Thanks!
> Should the code you sent before be a separate python file? Or should it be in the train.py file?

Hello,I want to embed the class word to,have you finished,and how to do it?would you mind to tell me how to do it?Thank you very much.
