### ISSUE TITLE
Picture scale problem

### ISSUE THREAD

**Issue by xieyuhaoli** [AnjanDutta/sem-pcyc#7]
Can I use images of any size for training and testing？

**Comment by AnjanDutta** [comment]
Yes, of course, it will be resized in the code

**Comment by xieyuhaoli** [comment]
Sorry, it may be a problem of my expression, ubecase my picture is rectangular, if the resize is square, the target will be deformed, will it affect the test result?Can I change the code so that I can extract features directly from the rectangle?I'm sorry, but I have one more question.If I use a different size for the same image, does it matter?

 



------------------ 原始邮件 ------------------
发件人: "Anjan Dutta"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 晚上10:53
收件人: "AnjanDutta/sem-pcyc"<sem-pcyc@noreply.github.com>; 
抄送: "宇"<2425225778@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AnjanDutta/sem-pcyc] Picture scale problem (#7)




Yes, of course, it will be resized in the code
