### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by xieyuhaoli** [AnjanDutta/sem-pcyc#8]
Sorry, it may be a problem of my expression, beacause my picture is rectangular, if the resize is square, the target will be deformed, will it affect the test result?Can I change the code so that I can extract features directly from the rectangle?I'm sorry, but I have one more question.If I use a different size for the same image, does it matter?

**Comment by AnjanDutta** [comment]
It should not make a lot of difference, don't worry about distorting the aspect ratio...

**Comment by xieyuhaoli** [comment]
OK，thank you
