### ISSUE TITLE
Problem in running dataset_download.sh

### ISSUE THREAD

**Issue by Anurag14** [AnjanDutta/sem-pcyc#9]
Respected Author, I am unable to run dataset_download successfully. My objective is to train and reproduce the results on TU Berlin and Sketchy dataset. I would be genuinely indebted if you can point out what am I missing? I have attached the logs of errors.
```
(sempcyc) anurag@iacvlab-desktop:/data/anurag/codes/baselines/sem-pcyc$ bash download_datasets.sh 
Downloading the Sketchy dataset (it will take some time)
32.0kB [00:00, 29.7MB/s]
Unzipping it...Done
rm: cannot remove '/data/anurag/sem/README.txt': No such file or directory
mv: cannot stat '/data/anurag/sem/256x256': No such file or directory
Downloading the extended photos of Sketchy dataset (it will take some time)
32.0kB [00:00, 33.6MB/s]
Unzipping it...[/data/anurag/sem/Sketchy/extended_photo.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /data/anurag/sem/Sketchy/extended_photo.zip or
        /data/anurag/sem/Sketchy/extended_photo.zip.zip, and cannot find /data/anurag/sem/Sketchy/extended_photo.zip.ZIP, period.
mv: cannot stat '/data/anurag/sem/Sketchy/EXTEND_image_sketchy': No such file or directory
mv: cannot stat '/data/anurag/sem/Sketchy/extended_photo/hot-air_balloon': No such file or directory
mv: cannot stat '/data/anurag/sem/Sketchy/extended_photo/jack-o-lantern': No such file or directory
Done
Sketchy dataset is now ready to be used
Downloading the sketches of TU-Berlin dataset (it will take some time)
--2019-10-03 20:51:13--  http://cybertron.cg.tu-berlin.de/eitz/projects/classifysketch/sketches_png.zip
Resolving cybertron.cg.tu-berlin.de (cybertron.cg.tu-berlin.de)... 130.149.80.52
Connecting to cybertron.cg.tu-berlin.de (cybertron.cg.tu-berlin.de)|130.149.80.52|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 550098987 (525M) [application/zip]
Saving to: ‘/data/anurag/sem/TU-Berlin/sketches.zip’

/data/anurag/sem/TU-Berli 100%[==================================>] 524.62M  7.97MB/s    in 69s     

2019-10-03 20:52:23 (7.63 MB/s) - ‘/data/anurag/sem/TU-Berlin/sketches.zip’ saved [550098987/550098987]

Unzipping it...mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flying bird': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/sponge bob': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/santa claus': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/standing bird': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/parking meter': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/person walking': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/walkie talkie': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/floor lamp': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/fire hydrant': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/computer monitor': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/sea turtle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flower with stem': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/bear (animal)': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/person sitting': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/bottle opener': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/race car': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/pickup truck': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/baseball bat': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/potted plant': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/power outlet': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/alarm clock': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/crane (machine)': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/traffic light': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/hot air balloon': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/car (sedan)': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/mouse (animal)': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/paper clip': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/pipe (for smoking)': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/space shuttle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/satellite dish': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/palm tree': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flying saucer': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/cell phone': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/door handle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/human-skeleton': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/hot-dog': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/frying-pan': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/beer-mug': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/speed-boat': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/t-shirt': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/ice-cream-cone': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/wine-bottle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/computer-mouse': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/wrist-watch': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/teddy-bear': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/head-phones': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/tennis-racket': No such file or directory
Done
Downloading the images of TU-Berlin dataset (it will take some time)
32.0kB [00:00, 37.3MB/s]
Unzipping it...[/data/anurag/sem/TU-Berlin/images.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /data/anurag/sem/TU-Berlin/images.zip or
        /data/anurag/sem/TU-Berlin/images.zip.zip, and cannot find /data/anurag/sem/TU-Berlin/images.zip.ZIP, period.
mv: cannot stat '/data/anurag/sem/TU-Berlin/ImageResized': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flyingbird': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spongebob': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/santaclaus': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/standingbird': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/parkingmeter': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/personwalking': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/walkietalkie': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/floorlamp': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/firehydrant': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/computermonitor': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/seaturtle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flowerwithstem': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/bearanimal': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/personsitting': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/bottleopener': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/racecar': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pickuptruck': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/baseballbat': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pottedplant': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/poweroutlet': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/alarmclock': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/cranemachine': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/trafficlight': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/hotairballoon': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/carsedan': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/mouse': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/paperclip': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pipe': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spacesshuttle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/satellitedish': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/palmtree': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flyingsaucer': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/cellphone': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/doorhandle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/humanskeleton': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/hotdog': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/fryingpan': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/beermug': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/speedboat': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tshirt': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/icecreamcone': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/winebottle': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/computermouse': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/wristwatching': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/teddybear': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/headphones': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tennisracket': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tromobone': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/chandeler': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/griaffe': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/diamod': No such file or directory
mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spidar': No such file or directory
find: ‘/data/anurag/sem/TU-Berlin/images’: No such file or directory
Done
TU-Berlin dataset is now ready to be used

```

**Comment by AnjanDutta** [comment]
Check the `path_dataset` and `path_aux` paths are set correctly in the config.ini. Also check if the datasets are getting downloaded correctly. I think there is some problem at your desktop so that the datasets are partially downloaded, it can find the `garbage.txt` and `Sketchy.7z` (at least not in your log), but cannot find the `README.txt`, it is strange.

**Comment by jiangyanjavawin** [comment]
> 
> 
> Respected Author, I am unable to run dataset_download successfully. My objective is to train and reproduce the results on TU Berlin and Sketchy dataset. I would be genuinely indebted if you can point out what am I missing? I have attached the logs of errors.
> 
> ```
> (sempcyc) anurag@iacvlab-desktop:/data/anurag/codes/baselines/sem-pcyc$ bash download_datasets.sh 
> Downloading the Sketchy dataset (it will take some time)
> 32.0kB [00:00, 29.7MB/s]
> Unzipping it...Done
> rm: cannot remove '/data/anurag/sem/README.txt': No such file or directory
> mv: cannot stat '/data/anurag/sem/256x256': No such file or directory
> Downloading the extended photos of Sketchy dataset (it will take some time)
> 32.0kB [00:00, 33.6MB/s]
> Unzipping it...[/data/anurag/sem/Sketchy/extended_photo.zip]
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /data/anurag/sem/Sketchy/extended_photo.zip or
>         /data/anurag/sem/Sketchy/extended_photo.zip.zip, and cannot find /data/anurag/sem/Sketchy/extended_photo.zip.ZIP, period.
> mv: cannot stat '/data/anurag/sem/Sketchy/EXTEND_image_sketchy': No such file or directory
> mv: cannot stat '/data/anurag/sem/Sketchy/extended_photo/hot-air_balloon': No such file or directory
> mv: cannot stat '/data/anurag/sem/Sketchy/extended_photo/jack-o-lantern': No such file or directory
> Done
> Sketchy dataset is now ready to be used
> Downloading the sketches of TU-Berlin dataset (it will take some time)
> --2019-10-03 20:51:13--  http://cybertron.cg.tu-berlin.de/eitz/projects/classifysketch/sketches_png.zip
> Resolving cybertron.cg.tu-berlin.de (cybertron.cg.tu-berlin.de)... 130.149.80.52
> Connecting to cybertron.cg.tu-berlin.de (cybertron.cg.tu-berlin.de)|130.149.80.52|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 550098987 (525M) [application/zip]
> Saving to: ‘/data/anurag/sem/TU-Berlin/sketches.zip’
> 
> /data/anurag/sem/TU-Berli 100%[==================================>] 524.62M  7.97MB/s    in 69s     
> 
> 2019-10-03 20:52:23 (7.63 MB/s) - ‘/data/anurag/sem/TU-Berlin/sketches.zip’ saved [550098987/550098987]
> 
> Unzipping it...mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flying bird': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/sponge bob': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/santa claus': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/standing bird': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/parking meter': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/person walking': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/walkie talkie': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/floor lamp': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/fire hydrant': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/computer monitor': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/sea turtle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flower with stem': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/bear (animal)': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/person sitting': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/bottle opener': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/race car': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/pickup truck': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/baseball bat': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/potted plant': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/power outlet': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/alarm clock': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/crane (machine)': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/traffic light': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/hot air balloon': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/car (sedan)': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/mouse (animal)': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/paper clip': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/pipe (for smoking)': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/space shuttle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/satellite dish': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/palm tree': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/flying saucer': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/cell phone': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/door handle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/human-skeleton': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/hot-dog': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/frying-pan': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/beer-mug': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/speed-boat': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/t-shirt': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/ice-cream-cone': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/wine-bottle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/computer-mouse': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/wrist-watch': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/teddy-bear': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/head-phones': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/sketches/tennis-racket': No such file or directory
> Done
> Downloading the images of TU-Berlin dataset (it will take some time)
> 32.0kB [00:00, 37.3MB/s]
> Unzipping it...[/data/anurag/sem/TU-Berlin/images.zip]
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /data/anurag/sem/TU-Berlin/images.zip or
>         /data/anurag/sem/TU-Berlin/images.zip.zip, and cannot find /data/anurag/sem/TU-Berlin/images.zip.ZIP, period.
> mv: cannot stat '/data/anurag/sem/TU-Berlin/ImageResized': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flyingbird': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spongebob': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/santaclaus': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/standingbird': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/parkingmeter': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/personwalking': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/walkietalkie': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/floorlamp': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/firehydrant': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/computermonitor': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/seaturtle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flowerwithstem': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/bearanimal': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/personsitting': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/bottleopener': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/racecar': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pickuptruck': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/baseballbat': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pottedplant': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/poweroutlet': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/alarmclock': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/cranemachine': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/trafficlight': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/hotairballoon': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/carsedan': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/mouse': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/paperclip': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/pipe': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spacesshuttle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/satellitedish': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/palmtree': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/flyingsaucer': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/cellphone': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/doorhandle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/humanskeleton': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/hotdog': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/fryingpan': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/beermug': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/speedboat': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tshirt': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/icecreamcone': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/winebottle': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/computermouse': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/wristwatching': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/teddybear': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/headphones': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tennisracket': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/tromobone': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/chandeler': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/griaffe': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/diamod': No such file or directory
> mv: cannot stat '/data/anurag/sem/TU-Berlin/images/spidar': No such file or directory
> find: ‘/data/anurag/sem/TU-Berlin/images’: No such file or directory
> Done
> TU-Berlin dataset is now ready to be used
> ```

Hello,Sir,I have the same error like you had,would you mind tell me how to solve the error to download the datasets and model?Thank you very much.

**Comment by Anurag14** [comment]
@jiangyanjavawin make sure your config.ini file has the correct details in them.

**Comment by jiangyanjavawin** [comment]
> @jiangyanjavawin make sure your config.ini file has the correct details in them.

Thank you very much,I have download the models,Buti I don't know what's the meaning of  semantic models,how to train these use my own datasets,I can train word2vec-google-news.npy,but I don't know how to use hieremb-lch,hieremb-lin,hieremb-path,hieremb-wup?
